#  ____  _            _______ _          _____
# |  _ \| |          |__   __| |        |  __ \
# | |_) | | __ _ _______| |  | |__   ___| |  | | _____   __
# |  _ <| |/ _` |_  / _ \ |  | '_ \ / _ \ |  | |/ _ \ \ / /
# | |_) | | (_| |/ /  __/ |  | | | |  __/ |__| |  __/\ V /
# |____/|_|\__,_/___\___|_|  |_| |_|\___|_____/ \___| \_/

# BlazinJoin Configuration File:
#   Default Config:
#     restart-time: 60
#     restart-message: "Server has been restarted"

# The below config is the auto restart time in minutes
restart-time: 60

# The below config is the message that will be sent when the server restarts
restart-message: "Server has been restarted"